<a href="https://colab.research.google.com/github/udhayprakash/PythonBatchNovDec2024/blob/class36/numpy_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




### Basics - creating Numpy array

Q) Difference between Python List and Numpy array?

Ans) numpy array is a list which contains **elements** of same data type only

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
print(dir(np))


['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__annotations__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [34]:
empty_arr = np.array([])
empty_arr

array([], dtype=float64)

In [35]:
int_arr = np.array([1, 2, 3, 4, 5])
int_arr

array([1, 2, 3, 4, 5])

In [36]:
int_arr = np.array([1, 2, 3, 4, 5], int)
int_arr

array([1, 2, 3, 4, 5])

In [38]:
int_arr = np.array([1, 2, 3, 4, 5], 'int32')
int_arr

array([1, 2, 3, 4, 5], dtype=int32)

In [39]:
str_arr = np.array(['ram', 'shyam', 'ganesh', 'mahesh', 'suresh'])
str_arr

array(['ram', 'shyam', 'ganesh', 'mahesh', 'suresh'], dtype='<U6')

In [40]:
str_arr = np.array(['ram', 'shyam', 'ganesh', 'mahesh', 'suresh'], str)
str_arr

array(['ram', 'shyam', 'ganesh', 'mahesh', 'suresh'], dtype='<U6')

In [120]:
complex_arr = np.array([1, 2, 3, 4, 5], dtype=np.complex64)
complex_arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j], dtype=complex64)

### List vs array

In [1]:
mylist = [1, 3.3, '234', None, True]

In [6]:
np.array([1, 3.3, '234', None, True])

array([1, 3.3, '234', None, True], dtype=object)

In [7]:
arr1 = np.array([1, 3.3, '234', None, True])
arr1

array([1, 3.3, '234', None, True], dtype=object)

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1.dtype

dtype('O')

In [10]:
arr2 = np.array([12340, 12341, 12342, 12343, 12345])

arr2

array([12340, 12341, 12342, 12343, 12345])

In [12]:
type(arr2)

numpy.ndarray

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr3 = np.array([12340, 12341, 12342, 12343, 12345], float)

arr3

array([12340., 12341., 12342., 12343., 12345.])

In [15]:
arr3.dtype

dtype('float64')

In [16]:
print(f'{len(arr1) =}')
print(f'{len(arr2) =}')
print(f'{len(arr3) =}')

len(arr1) =5
len(arr2) =5
len(arr3) =5


In [17]:
print(f'{arr1.shape =}')
print(f'{arr2.shape =}')
print(f'{arr3.shape =}')


arr1.shape =(5,)
arr2.shape =(5,)
arr3.shape =(5,)


### Multi-dimensional Arrays



In [18]:
arr4 = np.array([(1, 2, 3), (5, 6, 7)], float)

arr4

array([[1., 2., 3.],
       [5., 6., 7.]])

In [19]:
print(f'{len(arr4)  = }')
print(f'{arr4.shape = }')

len(arr4)  = 2
arr4.shape = (2, 3)


In [20]:
arr5 = np.array([ [1, 2, 3], (5, 6, 7)], float)
arr5

array([[1., 2., 3.],
       [5., 6., 7.]])

In [21]:
arr6 = np.array([ {1, 2, 3}, {5, 6, 7}], float)
arr6

TypeError: float() argument must be a string or a real number, not 'set'

### np.arrange

In [23]:
arr6 = np.arange(15)  # default start = 0, step = +1

print(f'{arr6       =}')
print(f'{len(arr6)  =}')
print(f'{arr6.dtype =}')
print(f'{arr6.shape =}')
print(f'{arr6.ndim  =}')  # the number of axes (dimensions) of the array.

arr6       =array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
len(arr6)  =15
arr6.dtype =dtype('int64')
arr6.shape =(15,)
arr6.ndim  =1


In [24]:
arr6 = np.arange(3, 15)  # default start = 0, step = +1

print(f'{arr6       =}')
print(f'{len(arr6)  =}')
print(f'{arr6.dtype =}')
print(f'{arr6.shape =}')
print(f'{arr6.ndim  =}')  # the number of axes (dimensions) of the array.

arr6       =array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
len(arr6)  =12
arr6.dtype =dtype('int64')
arr6.shape =(12,)
arr6.ndim  =1


In [25]:
arr6 = np.arange(3, 15, 2)  # default start = 0, step = +1

print(f'{arr6       =}')
print(f'{len(arr6)  =}')
print(f'{arr6.dtype =}')
print(f'{arr6.shape =}')
print(f'{arr6.ndim  =}')  # the number of axes (dimensions) of the array.

arr6       =array([ 3,  5,  7,  9, 11, 13])
len(arr6)  =6
arr6.dtype =dtype('int64')
arr6.shape =(6,)
arr6.ndim  =1


In [86]:
np.linspace(3, 15, 2) # here 2 is the number of element you want

array([ 3., 15.])

In [87]:
np.linspace(3, 15, 3) # here 3 is the number of element you want

array([ 3.,  9., 15.])

In [88]:
np.linspace(3, 15, 3)

array([ 3.,  9., 15.])

In [89]:
np.linspace(3, 15, 6)

array([ 3. ,  5.4,  7.8, 10.2, 12.6, 15. ])

In [90]:
np.linspace(3, 15, 12)  # step is calcuated dynamically, based on the number of values expected, from start, till end

array([ 3.        ,  4.09090909,  5.18181818,  6.27272727,  7.36363636,
        8.45454545,  9.54545455, 10.63636364, 11.72727273, 12.81818182,
       13.90909091, 15.        ])

In [91]:
np.linspace(3, 15, 898987987)

array([ 3.        ,  3.00000001,  3.00000003, ..., 14.99999997,
       14.99999999, 15.        ])

if we need to disable this displaying behaviour, use

np.set_printoptions(threshold=np.nan)

### np.reshape

In [26]:
arr6.reshape(3, 5) # 3 * 5 = 15

ValueError: cannot reshape array of size 6 into shape (3,5)

In [27]:
arr6.reshape(3, 2)  # 6 = 3 * 2

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

In [28]:
arr6.reshape(2, 3)  # 6 = 3 * 2

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [29]:
arr6

array([ 3,  5,  7,  9, 11, 13])

In [30]:
arr6 = arr6.reshape(2, 3)


arr6.ndim

2

### ndarray.itemsize



the size in bytes of each element of the array.
For example, an array of elements of type float64 has  8 (=6itemsize4/8),
while one of type complex32 has itemsize 4 (=32/8).
It is equivalent to ndarray.dtype.itemsize.

In [31]:
arr6

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [32]:
arr6.itemsize

8

In [33]:
print(f'{arr1 = } {arr1.itemsize =}')
print(f'{arr2 = } {arr2.itemsize =}')
print(f'{arr3 = } {arr3.itemsize =}')
print(f'{arr4 = } {arr4.itemsize =}')
print(f'{arr5 = } {arr5.itemsize =}')
print(f'{arr6 = } {arr6.itemsize =}')

arr1 = array([1, 3.3, '234', None, True], dtype=object) arr1.itemsize =8
arr2 = array([12340, 12341, 12342, 12343, 12345]) arr2.itemsize =8
arr3 = array([12340., 12341., 12342., 12343., 12345.]) arr3.itemsize =8
arr4 = array([[1., 2., 3.],
       [5., 6., 7.]]) arr4.itemsize =8
arr5 = array([[1., 2., 3.],
       [5., 6., 7.]]) arr5.itemsize =8
arr6 = array([[ 3,  5,  7],
       [ 9, 11, 13]]) arr6.itemsize =8


### creating array likes

In [42]:
arr6

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [43]:
np.zeros_like(arr6)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
np.ones_like(arr6)

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.ones((3, 4, 2), dtype=np.int16)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [50]:
np.ones((3, 4, 2), dtype=np.float128)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float128)

In [51]:
np.ones((3, 4, 2), dtype=np.float128) * 356

array([[[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]],

       [[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]],

       [[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]]], dtype=float128)

In [53]:
np.full((3, 4, 2), 356, dtype=np.float128)

array([[[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]],

       [[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]],

       [[356., 356.],
        [356., 356.],
        [356., 356.],
        [356., 356.]]], dtype=float128)

In [54]:
np.full((3, 3), 0.5, )

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [57]:
np.eye(3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(5 )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
# The eye function returns matrices with ones along the kth diagonal:

np.eye(5 , k=0)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(5 , k=2)


array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.eye(5 , k=-3)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [62]:
np.eye(5 , k=-67)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.identity(6, dtype=float)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [69]:
np.identity(6, dtype=float, like=arr6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [274]:
arr7 = np.identity(6, dtype=float, like=arr6)

np.trace(arr7) # trace - summation of principal diagonal eleements

6.0

In [70]:
arr6

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [74]:
np.version.full_version

'1.26.4'

In [75]:
! pip install numpy==2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 48.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.0 which is incompatible.
langchain 0.3.15 requires n

In [76]:
np.random.random((2, 3))  # Create an array filled with random values


array([[0.4959262 , 0.71572141, 0.98137696],
       [0.93870468, 0.54280569, 0.51495421]])

In [77]:
np.empty((2, 3))  # uninitialized, output may vary


array([[0.4959262 , 0.71572141, 0.98137696],
       [0.93870468, 0.54280569, 0.51495421]])

In [79]:
np.array([])

array([], dtype=float64)

In [80]:
np.random.random((2, 3))

array([[0.50371387, 0.06843771, 0.9113586 ],
       [0.19929773, 0.76767305, 0.84155286]])

In [81]:
np.empty((2, 3))


array([[0.50371387, 0.06843771, 0.9113586 ],
       [0.19929773, 0.76767305, 0.84155286]])

In [82]:
np.empty((2, 4))  # as they is not array of that dimenion, it created with random values


array([[2.913477e-316, 0.000000e+000, 0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000]])

In [83]:
np.random.random((2, 4))

array([[0.38793414, 0.04203469, 0.54827271, 0.40546048],
       [0.71439185, 0.8800557 , 0.25086557, 0.52191348]])

In [84]:
np.empty((2, 4))  #  empty will reuse exist8ing arrays, if created of that dimentsion


array([[0.38793414, 0.04203469, 0.54827271, 0.40546048],
       [0.71439185, 0.8800557 , 0.25086557, 0.52191348]])

### Arithmetic Opertaions

In [92]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)


In [95]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [96]:
a + b    # np.add(a, b)

array([20, 31, 42, 53])

In [97]:
a - b

array([20, 29, 38, 47])

In [98]:
a * b

array([  0,  30,  80, 150])

In [99]:
a / b

<ipython-input-99-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([        inf, 30.        , 20.        , 16.66666667])

In [100]:
b / a

array([0.        , 0.03333333, 0.05      , 0.06      ])

In [101]:
b //a

array([0, 0, 0, 0])

In [102]:
b % a

array([0, 1, 2, 3])

In [103]:
b  ** a

array([                  0,                   1,       1099511627776,
       6048575297968530377])

In [104]:
b  ** 2

array([0, 1, 4, 9])

In [105]:
print(f'{a.shape =}')
print(f'{b.shape =}')

a.shape =(4,)
b.shape =(4,)


In [106]:
c = np.arange(3)
c

array([0, 1, 2])

In [107]:
c.shape

(3,)

In [108]:
a + c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [109]:
10 * np.sin(a)  # element-wise multiplication


array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [110]:
a

array([20, 30, 40, 50])

In [111]:
a < 35

array([ True,  True, False, False])

In [112]:
# Assignment: compound operations , +=, -=, *=, /=, **=

In [113]:
A = np.array([[1, 1], [0, 1]])

B = np.array([[2, 0], [3, 4]])

In [114]:
A * B  # elementwise product


array([[2, 0],
       [0, 4]])

In [115]:
A @ B  # matrix product  - works only in Python >= 3.5

array([[5, 4],
       [3, 4]])

In [116]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [122]:
a

array([20, 30, 40, 50])

In [123]:
a.dtype

dtype('int64')

In [124]:
a.dtype.name

'int64'

In [125]:
a * 1j

array([0.+20.j, 0.+30.j, 0.+40.j, 0.+50.j])

In [127]:
d = np.exp(a * 1j)
d

array([ 0.40808206+0.91294525j,  0.15425145-0.98803162j,
       -0.66693806+0.74511316j,  0.96496603-0.26237485j])

In [128]:
d.dtype.name

'complex128'

In [277]:
a = np.array([2, 4, 3, 34, 324, 213, 12, 23, 34, 45, 67, -234], float)


In [278]:
print(f'{a.min() =}')
print(f'{a.max() =}')
print()

print(f'{a.sum()    =}')
print(f'{np.sum(a)  =}')
print()

# print(f'{a.trace()    =}')  # ValueError: diag requires an array of at least two dimensions
# print(f'{np.trace(a)  =}')
print()

print(f'{a.prod()   =}')
print(f'{np.prod(a) =}')
print()

print(f'{a.mean()   =}')
print(f'{np.mean(a) =}')
print()

print(f'{a.var()   =}')
print(f'{np.var(a) =}')
print()

print(f'{a.std()   =}')
print(f'{np.std(a) =}')

a.min() =-234.0
a.max() =324.0

a.sum()    =527.0
np.sum(a)  =527.0


a.prod()   =-3.728257888085453e+17
np.prod(a) =-3.728257888085453e+17

a.mean()   =43.916666666666664
np.mean(a) =43.916666666666664

a.var()   =15957.07638888889
np.var(a) =15957.07638888889

a.std()   =126.32132198836779
np.std(a) =126.32132198836779


In [135]:
a.shape

(12,)

In [136]:
a.reshape(3, 4)

array([[   2.,    4.,    3.,   34.],
       [ 324.,  213.,   12.,   23.],
       [  34.,   45.,   67., -234.]])

In [137]:
a

array([   2.,    4.,    3.,   34.,  324.,  213.,   12.,   23.,   34.,
         45.,   67., -234.])

In [279]:
a = a.reshape(3, 4)
a

array([[   2.,    4.,    3.,   34.],
       [ 324.,  213.,   12.,   23.],
       [  34.,   45.,   67., -234.]])

In [280]:
print(f'{a.min() =}')
print(f'{a.max() =}')
print()

print(f'{a.sum()    =}')
print(f'{np.sum(a)  =}')
print()


print(f'{a.trace()    =}')  # ValueError: diag requires an array of at least two dimensions
print(f'{np.trace(a)  =}')
print()

print(f'{a.prod()   =}')
print(f'{np.prod(a) =}')
print()

print(f'{a.mean()   =}')
print(f'{np.mean(a) =}')
print()

print(f'{a.var()   =}')
print(f'{np.var(a) =}')
print()

print(f'{a.std()   =}')
print(f'{np.std(a) =}')

a.min() =-234.0
a.max() =324.0

a.sum()    =527.0
np.sum(a)  =527.0

a.trace()    =282.0
np.trace(a)  =282.0
a.prod()   =-3.728257888085453e+17
np.prod(a) =-3.728257888085453e+17

a.mean()   =43.916666666666664
np.mean(a) =43.916666666666664

a.var()   =15957.07638888889
np.var(a) =15957.07638888889

a.std()   =126.32132198836779
np.std(a) =126.32132198836779


The argmin and argmax functions return the array indices of the minimum and maximum values



In [141]:
a = np.array([2, 4, 3, 34, 324, 213, 12, 23, 34, 45, 67, -234], float)
#             0  1  2   3   4    5    6   7   8   9  10    11
print(f"a.argmin(): {a.argmin()}")
print(f"a.argmax(): {a.argmax()}")

a.argmin(): 11
a.argmax(): 4


In [143]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)  # dim - 3, 1, 2

a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [146]:
print(f"a.mean()      :{a.mean()}")
print(f"a.mean(axis=0):{a.mean(axis=0)}")  # (0 + 3 + 3)/3
print(f"a.mean(axis=1):{a.mean(axis=1)}")  # (0 +2)/2, (3-1)/2 , ...

a.mean()      :2.0
a.mean(axis=0):[2. 2.]
a.mean(axis=1):[1. 1. 4.]


In [147]:
a.shape

(3, 2)

In [148]:
a = np.array([6, 2, 5, -1, 0], float)
print(f"sorted(a): {sorted(a)}")
print(f"a        : {a}")

sorted(a): [-1.0, 0.0, 2.0, 5.0, 6.0]
a        : [ 6.  2.  5. -1.  0.]


In [149]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

Values in an array can be "clipped" to be within a prespecified range. This is the same as applying min(max(x, minval), maxval) to each element x in an array.



In [151]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [152]:
a = np.array([6, 6, 1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)  # unique sorted ascending

array([1., 4., 5., 6., 7.])

In [153]:
# For two dimensional arrays, the diagonal can be extracted:

a = np.array([[1, 2], [3, 4]], float)
# [
#     [1, 2],
#     [3, 4]
# ]

a.diagonal()

array([1., 4.])

In [154]:
x = np.array([[1, 2], [3, 4]])

print(x, np.sum(x))  # Compute sum of all elements; prints "10"

[[1 2]
 [3 4]] 10


In [155]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"


[4 6]


In [156]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


[3 7]


In [157]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
b.cumsum(axis=1)  # cumulative sum along each row


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [159]:
b.cumsum(axis=0)  # cumulative sum along each column


array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [160]:
b.cumsum()


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [161]:
b.sum()

66

In [164]:
B = np.arange(3)
B

array([0, 1, 2])

In [165]:
np.sqrt(B)


array([0.        , 1.        , 1.41421356])

In [166]:
B ** 0.5

array([0.        , 1.        , 1.41421356])

In [168]:
b ** (1/2)  # PEMDAS

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [169]:
b ** (1/3)  # PEMDAS

array([[0.        , 1.        , 1.25992105, 1.44224957],
       [1.58740105, 1.70997595, 1.81712059, 1.91293118],
       [2.        , 2.08008382, 2.15443469, 2.22398009]])

### Array concatenation


In [170]:
a = np.array([1, 2], float)
b = np.array([3, 4, 5, 6], float)
c = np.array([7, 8, 9], float)

np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [171]:
try:
    a + b + c
except ValueError as ex:
    print(ex)

operands could not be broadcast together with shapes (2,) (4,) 


If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default (without specifying the axis), NumPy concatenates along the first dimension:



In [172]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)

In [173]:
try:
    np.concatenate(a, b)
except TypeError as ex:
    print(ex)

only integer scalar arrays can be converted to a scalar index


In [174]:
np.concatenate((a, b))


array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [175]:
np.concatenate((a, b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [176]:
np.concatenate((a, b), axis=1)


array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

### Indexing, Slicing and Iterating


One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [177]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [178]:
a[2]


8

In [179]:
a[2:5]


array([ 8, 27, 64])

In [180]:
a[:6:2]


array([ 0,  8, 64])

In [181]:
# array is mutable object

a[:6:2] = -1000  # equivalent to a[0:6:2] = -1000


In [182]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [183]:
a[::-1]  # reversed a


array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [184]:
for i in a:
    print(i, i ** (1 / 3.0))

-1000 nan
1 1.0
-1000 nan
27 3.0
-1000 nan
125 4.999999999999999
216 5.999999999999999
343 6.999999999999999
512 7.999999999999999
729 8.999999999999998


<ipython-input-184-95c51286ee35>:2: RuntimeWarning: invalid value encountered in power
  print(i, i ** (1 / 3.0))


In [185]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [186]:
n = m[:2, 1:3]

n

array([[2, 3],
       [6, 7]])

In [187]:
m[0, 1]


2

In [188]:
n[0, 0] = 77  # n[0, 0] is the same piece of data as m[0, 1]
n

array([[77,  3],
       [ 6,  7]])

In [189]:
m[0, 1]


77

In [190]:
m


array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [192]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

def f(x, y):
    return 10 * x + y


b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [193]:
b[2, 3]


23

In [194]:
b[0:5, 1]  # each row in the second column of b


array([ 1, 11, 21, 31, 41])

In [195]:
b[:, 1]  # equivalent to the previous example


array([ 1, 11, 21, 31, 41])

In [196]:
b[1:3, :]  # each column in the second and third row of b


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [197]:
b[-1]  # the last row. Equivalent to b[-1,:]


array([40, 41, 42, 43])

In [199]:
c = np.array(
    [
        [
            [0, 1, 2],
            [10, 12, 13]
        ],  # a 3D array (two stacked 2D arrays)
        [[100, 101, 102], [110, 112, 113]],
    ]
)

c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [200]:
c.shape


(2, 2, 3)

In [201]:
c[1, ...]  # same as c[1,:,:] or c[1]


array([[100, 101, 102],
       [110, 112, 113]])

In [202]:
c[..., 2]  # same as c[:,:,2]


array([[  2,  13],
       [102, 113]])

In [203]:
# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [210]:
b.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [209]:
b.flat[10]  # 10th element, after flattening is 22

22

In [211]:
b.shape


(5, 4)

In [212]:
b = b.flatten()
b.shape

(20,)

In [213]:
b.ravel()  # returns the array, flattened

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [214]:
b

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [215]:
a = np.floor(10 * np.random.random((3, 4)))

a

array([[7., 5., 4., 7.],
       [6., 9., 0., 7.],
       [5., 0., 6., 6.]])

In [217]:
a.flatten()

print(a)
print(a.shape)

[[7. 5. 4. 7.]
 [6. 9. 0. 7.]
 [5. 0. 6. 6.]]
(3, 4)


In [218]:
a.ravel()

print(a)
print(a.shape)

[[7. 5. 4. 7.]
 [6. 9. 0. 7.]
 [5. 0. 6. 6.]]
(3, 4)


In [ ]:
# Quetsion: np.flatten vs np.ravel

In [219]:
a

array([[7., 5., 4., 7.],
       [6., 9., 0., 7.],
       [5., 0., 6., 6.]])

In [220]:
a.T

array([[7., 6., 5.],
       [5., 9., 0.],
       [4., 0., 6.],
       [7., 7., 6.]])

In [221]:
np.transpose(a)

array([[7., 6., 5.],
       [5., 9., 0.],
       [4., 0., 6.],
       [7., 7., 6.]])

In [222]:
a.shape, np.transpose(a).shape

((3, 4), (4, 3))

In [223]:
a

array([[7., 5., 4., 7.],
       [6., 9., 0., 7.],
       [5., 0., 6., 6.]])

In [224]:
a.resize((2, 6))
a

array([[7., 5., 4., 7., 6., 9.],
       [0., 7., 5., 0., 6., 6.]])

In [225]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

a.reshape(3, -1)


array([[7., 5., 4., 7.],
       [6., 9., 0., 7.],
       [5., 0., 6., 6.]])

### Stacking together different arrays
Several arrays can be stacked together along different axes:

> Add blockquote



In [226]:
x = np.arange(0, 10, 2)  # x=([0,2,4,6,8])
y = np.arange(5)  # y=([0,1,2,3,4])

In [227]:
x

array([0, 2, 4, 6, 8])

In [228]:
y

array([0, 1, 2, 3, 4])

In [229]:
np.vstack([x, y])  # concate ais 0

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [230]:
np.hstack([x, y])  # flatten


array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [231]:
a = np.floor(10 * np.random.random((2, 2)))
a

array([[2., 7.],
       [8., 9.]])

In [232]:
b = np.floor(10 * np.random.random((2, 2)))
b

array([[3., 1.],
       [8., 9.]])

In [233]:
np.vstack((a, b))  # Horizontal Append  -- np.concatenate(axis=0)


array([[2., 7.],
       [8., 9.],
       [3., 1.],
       [8., 9.]])

In [234]:
np.hstack((a, b))  # Vertical Append -- np.concatenate(axis=1)


array([[2., 7., 3., 1.],
       [8., 9., 8., 9.]])

In [235]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

np.column_stack((a, b))  # with 2D arrays


array([[2., 7., 3., 1.],
       [8., 9., 8., 9.]])

In [236]:
a = np.array([4.0, 2.0])
b = np.array([3.0, 8.0])

np.column_stack((a, b))  # returns a 2D array


array([[4., 3.],
       [2., 8.]])

In [237]:
np.hstack((a, b))  # the result is different


array([4., 2., 3., 8.])

In [238]:
np.vstack((a, b))


array([[4., 2.],
       [3., 8.]])

In [239]:
from numpy import newaxis

a[:, newaxis]  # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [240]:
np.column_stack((a[:, newaxis], b[:, newaxis]))


array([[4., 3.],
       [2., 8.]])

In [241]:
np.hstack((a[:, newaxis], b[:, newaxis]))  # the result is the same


array([[4., 3.],
       [2., 8.]])

### Splitting one array into several smaller ones


In [242]:
a = np.floor(10 * np.random.random((2, 12)))
a

array([[7., 0., 1., 5., 8., 8., 9., 5., 4., 7., 7., 3.],
       [7., 6., 3., 0., 7., 0., 2., 9., 3., 2., 8., 4.]])

In [243]:
print(np.hsplit(a, 3))  # Split a into 3


[array([[7., 0., 1., 5.],
       [7., 6., 3., 0.]]), array([[8., 8., 9., 5.],
       [7., 0., 2., 9.]]), array([[4., 7., 7., 3.],
       [3., 2., 8., 4.]])]


In [244]:
np.hsplit(a, (3, 4))  # Split a after the third and the fourth column

[array([[7., 0., 1.],
        [7., 6., 3.]]),
 array([[5.],
        [0.]]),
 array([[8., 8., 9., 5., 4., 7., 7., 3.],
        [7., 0., 2., 9., 3., 2., 8., 4.]])]

In [ ]:
# vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.



### Copies and Views

No Copy at All

Simple assignments make no copy of array objects or of their data.

In [245]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [246]:
b = a  # no new object is created


In [247]:
b is a  # a and b are two names for the same ndarray object


True

In [248]:
id(a), id(b)


(135911969290256, 135911969290256)

In [249]:
b.shape = 3, 4  # changes the shape of a
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [250]:
a.shape

(3, 4)

#### View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.



In [251]:
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [252]:
c is a

False

In [253]:
id(a), id(b), id(c)


(135911969290256, 135911969290256, 135911969290928)

In [254]:
c.base is a  # c is a view of the data owned by a


True

In [255]:
c.flags.owndata


False

In [256]:
c.shape = 2, 6  # a's shape doesn't change


In [257]:
a.shape


(3, 4)

In [258]:
c[0, 4] = 1234  # a's data changes


In [259]:
print(c)


[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [260]:
print(a)


[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [261]:
# Slicing an array returns a view of it:

s = a[:, 1:3]  # spaces added for clarity; could also be written "s = a[:,1:3]"


In [262]:
s[:] = 10  # s[:] is a view of s. Note the difference between s=10 and s[:]=10


In [263]:
a


array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.

In [264]:
d = a.copy()  # a new array object with new data is created

d is a

False

In [265]:
d.base is a  # d doesn't share anything with a


False

In [266]:
d.flags.owndata


True

In [267]:
d[0, 0] = 9999

a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Broadcasting rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.


After application of the broadcasting rules, the sizes of all arrays must match.




##### Indexing with Arrays of Indices


In [268]:
a = np.arange(12) ** 2  # the first 12 square numbers
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [269]:
i = np.array([1, 1, 3, 8, 5])  # an array of indices


In [270]:
a[i]


array([ 1,  1,  9, 64, 25])

In [271]:
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices


In [272]:
a[j]  # the same shape as j


array([[ 9, 16],
       [81, 49]])

In [273]:
palette = np.array(
    [
        [0, 0, 0],    # black
        [255, 0, 0],  # red
        [0, 255, 0],  # green
        [0, 0, 255],  # blue
        [255, 255, 255],
    ]
)  # white

image = np.array(
    [[0, 1, 2, 0], [0, 3, 4, 0]]  # each value corresponds to a color in the palette
)

print(palette[image])  # the (2,4,3) color image

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]


### np.linalg

In [282]:
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [283]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [284]:
y = np.array([[5.0], [7.0]])


In [285]:
np.linalg.solve(a, y)


array([[-3.],
       [ 4.]])

In [286]:
np.linalg.eig(j)


EigResult(eigenvalues=array([-1.32455532, 11.32455532]), eigenvectors=array([[-0.67902243, -0.43310182],
       [ 0.73411752, -0.901345  ]]))